### ISSUE TITLE
Doble foto en contacto

### ISSUE THREAD

**Issue by AylenOrtiz** [Adalab/d-s1-dracarys#10]
Se ha duplicado la foto del ojo del dragón.

**Comment by annabranco** [comment]
## Corregido a través del commit de1b2ea.
El problema estaba porque la class de la foto de fondo de *Contacto* era la misma lass del *Index*, entonces estaba usando todas los mismos estilos de la foto HERO de la página principal.
Y además el <img> seguía en el HTML.
