### ISSUE TITLE
Problema para colocar texto "equipo"

### ISSUE THREAD

**Issue by ashesnei** [Adalab/d-s1-dracarys#3]
No consigo colocar el texto de equipo en mediaqueries Desktop (En canción de hielo[...]abordar los problemas y encontrar soluciones.)
Intento centrarlo y darle un ancho indicado que es de 601px (o ancho máximo, lo que cuele) y se posiciona a la izquierda ¬_¬ ni con flex lo consigo.

**Comment by annabranco** [comment]
Corregido a través del commit 0e7f6cc.

El problema básicamente ocurría porque *Equipo* estaba insertado en el mismo <div> de *Fortalezas y Debilidades*, donde el alineamiento de este interfería con lo de *Equipo*.

Como solución he aislado ls dos partes en <div>s distintos, que llevan la misma clase ::.equipo-txt:: , por fins de garantizar el formato correcto. He creado aún una clase ::.description:: solo para hacer pequeños cambios en el formato de *Equipo*.

Con la creación del nuevo <div>, he reconfigurado el triangulo para adaptarse al nuevo formato, lo que parece funcionar bien. :)
